parameters:
    oro_entity.audit_datagrid.manager.class:               Oro\Bundle\EntityBundle\Datagrid\AuditDatagridManager

services:
    oro_entity.audit_datagrid.manager:
        class:  %oro_entity.audit_datagrid.manager.class%
        arguments:
          - @oro_entity_config.config_manager
        tags:
            - name:                             oro_grid.datagrid.manager
              datagrid_name:                    entity_audit
              entity_name:                      Oro\Bundle\EntityConfigBundle\Entity\ConfigLog
              entity_hint:                      entity_audit
              route_name:                       oro_entity_audit
              query_entity_alias:               ea
