datagrid:
    custom-entity-grid:
        options:
            entityHint: entity
        source:
            acl_resource: ~
            type: orm
            query:
                select:
                    - ce.id
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }

        columns: ~ # no static columns

        properties:
            update_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_subscriber->getLinkProperty
                route: oro_entity_update
                params:
                    - id
            view_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_subscriber->getLinkProperty
                route: oro_entity_view
                params:
                    - id
            delete_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_subscriber->getLinkProperty
                route: oro_entity_delete
                params:
                    - id

        actions:
            # TODO: add dynamic acl_resources
            view:
                type: navigate
                label: View
                icon: book
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: Update
                icon: edit
                link: update_link
            delete:
                type: delete
                label: Delete
                icon: trash
                link: delete_link

        sorters: ~ # no pre-defined sorters
        filters: ~

    entity-relation-grid:
        options:
            entityHint: entity
        source:
            acl_resource: ~
            type: orm
            query:
                select:
                    - ce.id
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }

