datagrid:
    custom-entity-grid:
        options:
            entityHint: entity
        source:
            acl_resource: ~
            type: orm
            query:
                select:
                    - ce.id
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }

    entity-relation-grid:
        options:
            entityHint: entity
        source:
            acl_resource: ~
            type: orm
            query:
                select:
                    - ce.id
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }

