TestClassExtend:
    is_extend:                      true                    #default false
    configs:                                                #config for entity
        entity:
            label:                  TestClassExtend
    fields:
        testStringField:
            owner:                  'Custom'
            type:                   string
            configs:
                entity:
                    label:          testStringField
            options:
                length:             200
        testIntegerField:
            owner:                  'Custom'
            type:                   smallint


OroCRM\Bundle\ContactBundle\Entity\Contact:
    fields:
        testField:
            type:                   string
