oro_entity_config:
    entity:
        entity:
            form:
                block_config:
                    entity:
                        title:              'General'
                        priority:           20

            items:
                icon:
                    options:
                        priority:           10
                    constraints:
                        - NotBlank:         ~
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                label:
                    options:
                        priority:           20
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               string
                        label:              'Label'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                plural_label:
                    options:
                        priority:           35
                    constraints:
                        - Length:
                            min:            2
                            max:            50
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true


                description:
                    options:
                        priority:           50
                    constraints:
                        - Length:
                            max:            500
                    grid:
                        type:               text
                        label:              'Description'
                        filter_type:        oro_grid_orm_string
                        required:           false
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false
        field:
            form:
                block_config:
                    entity:
                        title:              'General'
                        priority:           20
            items:
                label:
                    options:
                        priority:           10
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               string
                        label:              'Label'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                description:
                    options:
                        priority:           30
                    constraints:
                        - Length:
                            max:            500
                    grid:
                        type:               text
                        label:              'Description'
                        filter_type:        oro_grid_orm_string
                        required:           false
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false

    datagrid:
        field:
            items:
                is_searchable:
                    options:
                        default_value:      false
                    grid:
                        type:               boolean
                        label:              'Grid'
                        filter_type:        oro_grid_orm_boolean
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          'Grid'
