TestClassExtend:
    is_extend:                      true
    configs:
        entity:
            label:                  TestClassExtend
    fields:
        testStringField:
            type:                   string
            configs:
                entity:
                    label:          testStringField
            options:
                length:             200
        testIntegerField:
            type:                   smallint
        testHiddenField:
            mode:                   hidden
            type:                   string
        testReadonlyField:
            mode:                   readonly
            type:                   string

TestClassExtend2:
    is_extend:                      false
    configs:
        entity:
            label:                  TestClassExtend2
    fields:
        testStringField2:
            type:                   string
            configs:
                entity:
                    label:          testStringField2
            options:
                length:             200

Oro\Bundle\UserBundle\Entity\User:
    fields:
        testField:
            type:                   string
        testHiddenField:
            mode:                   hidden
            type:                   string
        testReadonlyField:
            mode:                   readonly
            type:                   string
