oro_entity_config:
    entity:
        entity:
            form:
                block_config:
                    entity:
                        priority:           20
            items:
                icon:
                    options:
                        priority:           10
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true
                label:
                    options:
                        priority:           20
                    grid:
                        type:               string
                        label:              'Label'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true
                plural_label:
                    options:
                        priority:           30
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true
                description:
                    options:
                        priority:           50
                    grid:
                        type:               text
                        label:              'Description'
                        filter_type:        oro_grid_orm_string
                        required:           false
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false
        field:
            items:
                label:
                    options:
                        priority:           10
                    grid:
                        type:               string
                        label:              'Label'
                        filter_type:        oro_grid_orm_string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true
                description:
                    options:
                        priority:           30
                    grid:
                        type:               text
                        label:              'Description'
                        filter_type:        oro_grid_orm_string
                        required:           false
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false

    datagrid:
        field:
            form:
                block_config:
                    datagrid:
                        title:              'Datagrid Config'
                        subblocks:
                            base:           ~
            items:
                is_searchable:
                    options:
                        default_value:      false
                        is_bool:            true
                    grid:
                        type:               boolean
                        label:              'Grid'
                        filter_type:        oro_grid_orm_boolean
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        false
                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          datagrid
                            label:          'Grid'
