oro_entity_config:
    entity:
        entity:
            form:
                block_config:
                    entity:
                        title:              'General'
                        priority:           20

            items:
                icon:
                    options:
                        priority:           10
                    form:
                        type:               oro_icon_select
                        options:
                            block:          entity
                label:
                    options:
                        priority:           20
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               html
                        label:              'Label'
                        filter_type:        string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                        template:           OroEntityConfigBundle:Config:propertyLabel.html.twig
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                plural_label:
                    options:
                        priority:           35
                    constraints:
                        - Length:
                            min:            2
                            max:            50
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                description:
                    options:
                        priority:           50
                    constraints:
                        - Length:
                            max:            500
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false
        field:
            form:
                block_config:
                    entity:
                        title:              'General'
                        priority:           20
            items:
                label:
                    options:
                        priority:           10
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            50
                    grid:
                        type:               string
                        label:              'Label'
                        filter_type:        string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false
                    form:
                        type:               text
                        options:
                            block:          entity
                            required:       true

                description:
                    options:
                        priority:           30
                    constraints:
                        - Length:
                            max:            500
                    form:
                        type:               textarea
                        options:
                            block:          entity
                            required:       false

    datagrid:
        field:
            items:
                is_visible:
                    options:
                        default_value:      true
                        allowed_type:       [string,integer,smallint,bigint,boolean,decimal,date,text,float]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom

                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          'Show on grid'

    form:
        field:
            items:
                is_enabled:
                    options:
                        default_value:      true
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom

                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          'Show on form'

    view:
        field:
            items:
                is_displayable:
                    options:
                        default_value:      true
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom

                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          'Show on view'
