TestClassExtend:
    fields:
        testStringField:
            type:               string
            options:
                length:         200
        testIntegerField:
            type:               smallint
        testHiddenField:
            mode:               hidden
            type:               string
        testReadonlyField:
            mode:               readonly
            type:               string

TestClassExtend2:
    type:                       Custom
    fields:
        testStringField:
            type:               string
            options:
                length:         200

Oro\Bundle\UserBundle\Entity\User:
    fields:
        testField:
            type:               string
        testHiddenField:
            mode:               hidden
            type:               string
        testReadonlyField:
            mode:               readonly
            type:               string
