parameters:
    oro_entity.form.type.custom_entity.class:                  Oro\Bundle\EntityBundle\Form\Type\CustomEntityType

services:
    oro_entity.form.type.custom_entity:
        class:                                                 %oro_entity.form.type.custom_entity.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: custom_entity_type }
