parameters:
    oro_entity.form.type.custom_entity.class:                  Oro\Bundle\EntityBundle\Form\Type\CustomEntityType
    oro_entity.form.type.entity_select.class:                  Oro\Bundle\EntityBundle\Form\Type\EntitySelectType

services:
    oro_entity.form.type.custom_entity:
        class:                                                 %oro_entity.form.type.custom_entity.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: custom_entity_type }

    oro_entity.form.type.entity_select:
        class:                                                 %oro_entity.form.type.entity_select.class%
        tags:
            - { name: form.type, alias: oro_entity_select_type }


#    orocrm_contact.form.autocomplete.contact.search_handler:
#        parent: oro_form.autocomplete.search_handler
#        arguments:
#            - %orocrm_contact.entity.class%
#            - ["first_name", "last_name"]
#        tags:
#            - { name: oro_form.autocomplete.search_handler, alias: contacts, acl_resource: orocrm_contact_view }


