parameters:
    oro_entity.metadata.metadata_factory.class:             Metadata\MetadataFactory
    oro_entity.metadata.cache.file_cache.class:             Metadata\Cache\FileCache
    oro_entity.metadata.audit.chain_driver.class:           Metadata\Driver\DriverChain
    oro_entity.metadata.audit.annotation_driver.class:      Oro\Bundle\EntityBundle\Metadata\Driver\AuditAnnotationDriver
    oro_entity.metadata.audit.config_driver.class:          Oro\Bundle\EntityBundle\Metadata\Driver\AuditConfigDriver

services:
    oro_entity.metadata.audit.metadata_factory:
        class:                                              %oro_entity.metadata.metadata_factory.class%
        arguments:                                          [@oro_entity.metadata.audit.chain_driver]
        public:                                             false
        calls:
            - [setCache, [@oro_entity.metadata.audit.file_cache]]

    oro_entity.metadata.audit.chain_driver:
        class:                                              %oro_entity.metadata.audit.chain_driver.class%
        arguments:                                          [[@oro_entity.metadata.audit.annotation_driver, @oro_entity.metadata.audit.config_driver]]

    oro_entity.metadata.audit.annotation_driver:
        class:                                              %oro_entity.metadata.audit.annotation_driver.class%
        arguments:                                          [@annotation_reader]
        public:                                             false

    oro_entity.metadata.audit.config_driver:
        class:                                              %oro_entity.metadata.audit.config_driver.class%
        arguments:                                          [@oro_entity.config.audit_config_provider]
        public:                                             false

    oro_entity.metadata.audit.file_cache:
        class:                                              %oro_entity.metadata.cache.file_cache.class%
        arguments:                                          [%oro_entity.cache_dir.audit%]
        public:                                             false
