parameters:
    oro_entity.listener.navigation_listener.class: Oro\Bundle\EntityBundle\EventListener\NavigationListener

services:
    oro_entity.listener.navigation_listener:
        class: %oro_entity.listener.navigation_listener.class%
        arguments:
            - @oro_security.security_facade
            - @doctrine.orm.entity_manager
            - @oro_entity_config.provider.entity
            - @oro_entity_config.provider.extend
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }
