parameters:
    oro_entity.listener.config_subscriber.class:            Oro\Bundle\EntityBundle\EventListener\ConfigSubscriber
    oro_entity.listener.doctrine_subscriber.class:          Oro\Bundle\EntityBundle\EventListener\DoctrineSubscriber
    oro_entity.audit.audit_manager.class:                   Oro\Bundle\EntityBundle\Audit\AuditManager

services:
    oro_entity.audit.audit_manager:
        class:                                              %oro_entity.audit.audit_manager.class%
        arguments:                                          [@oro_entity.config.audit_config_provider, @oro_entity.metadata.audit.metadata_factory]

    oro_entity.listener.doctrine_subscriber:
        class:                                              %oro_entity.listener.doctrine_subscriber.class%
        arguments:                                          [@oro_entity.audit.audit_manager]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    oro_entity.listener.config_subscriber:
        class:                                              %oro_entity.listener.config_subscriber.class%
#        arguments:                                          [@oro_entity.config.entity_config_provider]
        tags:
            - { name: kernel.event_subscriber}

    oro_entity.config.entity_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: entity }

    oro_entity.config.datagrid_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: datagrid }

    oro_entity.config.audit_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: audit }
