parameters:
#    oro_entity.example.class: Oro\Bundle\EntityBundle\Example

services:
#    oro_entity.example:
#        class: %oro_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
