parameters:
    oro_entity.listener.config_subscriber.class:            Oro\Bundle\EntityBundle\EventListener\ConfigSubscriber

services:
    oro_entity.listener.config_subscriber:
        class:                                              %oro_entity.listener.config_subscriber.class%
#        arguments:                                          [@oro_entity.config.entity_config_provider]
        tags:
            - { name: kernel.event_subscriber}

    oro_entity.config.entity_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: entity }

#    oro_entity.config.datagrid_config_provider:
#        tags:
#            - { name: oro_entity_config.provider, scope: datagrid }
