parameters:
    oro_entity.orm.query.filter_collection.class: Oro\Bundle\EntityBundle\ORM\Query\FilterCollection
    oro_filter: Oro\Bundle\EntityBundle\Filter\Filter

services:
    oro_entity.config.entity_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: entity }

    oro_entity.config.datagrid_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: datagrid }

    oro_entity.orm.query.filter_collection:
        class:             %oro_entity.orm.query.filter_collection.class%
        arguments:         ["@doctrine.orm.entity_manager"]

    oro_entity.filter:
          class:           %oro_filter%
          arguments:       ["@doctrine.orm.entity_manager"]
          tags:
               - { name: oro_entity.sql_filter, filter_name: customFilter, enabled: true }