parameters:
    doctrine.orm.entity_manager.class:            Oro\Bundle\EntityBundle\ORM\OroEntityManager

    oro_entity.entity.owners:
        organization: "OroOrganizationBundle:Organization"
        business_unit: "OroOrganizationBundle:BusinessUnit"
        user: "OroUserBundle:User"
    oro_entity.orm.query.filter_collection.class: Oro\Bundle\EntityBundle\ORM\Query\FilterCollection
    oro_filter: Oro\Bundle\EntityBundle\Filter\Filter

    oro_entity.orm.entity_class_resolver.class:                Oro\Bundle\EntityBundle\ORM\EntityClassResolver
    oro_entity.orm.entity_class_accessor.class:                Oro\Bundle\EntityBundle\ORM\EntityClassAccessor
    oro_entity.orm.entity_owner_accessor.class:                Oro\Bundle\EntityBundle\Owner\EntityOwnerAccessor
    oro_entity.owner.ownership_metadata_provider.class:        Oro\Bundle\EntityBundle\Owner\Metadata\OwnershipMetadataProvider
    oro_entity.owner.ownership_metadata_provider.cache_impl.class: Doctrine\Common\Cache\FilesystemCache

services:
    oro_entity_config.link.provider_bag.method:
        tags:
            - { name: oro_service_method,  service: oro_entity_config.provider_bag, method: testAction }

    oro_entity.orm.entity_class_resolver:
        class: %oro_entity.orm.entity_class_resolver.class%
        arguments:
            - @doctrine

    oro_entity.orm.entity_class_accessor:
        class: %oro_entity.orm.entity_class_accessor.class%

    oro_entity.orm.entity_owner_accessor:
        class: %oro_entity.orm.entity_owner_accessor.class%
        arguments:
            - @oro_entity.orm.entity_class_accessor
            - @oro_entity.owner.ownership_metadata_provider

    oro_entity.owner.ownership_metadata_provider:
        class: %oro_entity.owner.ownership_metadata_provider.class%
        arguments:
            - %oro_entity.entity.owners%
            - @oro_entity_config.provider.ownership
            - @oro_entity.orm.entity_class_resolver
            - @oro_entity.owner.ownership_metadata_provider.cache_impl

    oro_entity.owner.ownership_metadata_provider.cache_impl:
        public: false
        class: %oro_entity.owner.ownership_metadata_provider.cache_impl.class%
        arguments:
            - %kernel.cache_dir%/oro_ownership_metadata
